apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sjm-py-tastpa-7
  janus-idp.io/tekton: sjm-py-tastpa-7
  backstage.io/kubernetes-id: sjm-py-tastpa-7
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sjm-py-tastpa-7
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
